version: '2'
services:
  server:
    build: .
    volumes:
      - './data/html:/home/webapp/html'
      - './data/ssh:/home/webapp/.ssh'
    ports:
      - "8080:80"
      - "8022:22"

# docker-compose -f docker-compose.dev.yml up --build